### ISSUE TITLE
Download dataset with less ROIs

### ISSUE THREAD

**Issue by sara-silvaad** [Anwar-Said/NeuroGraph#2]
Hello! I've been working with the NeuroGraph dataset on a project and now I want to run some tests on the same dataset with fewer ROIS. I've been reading the documentation and I saw that there is a preprocess function in utils and that NeuroGraphDataset also could take a pre_transform function. However, the preprocess function, as far as I can see, doesn't apply to a torch_geometric.data.Data object. Is there a way for me to import the NeuroGraphDataset HCPAge but with less that 1000 ROIs? 

Thank you!

**Comment by Anwar-Said** [comment]
Thank you for using NeuroGraph. Unfortunately, the benchmarks we offer are based on 1000 ROIs in resting state setting. However, you can use utils.preprocess() function for preprocessing if you have already downloaded the dataset. Otherwise, please use Brain_Connectome_Rest_Download class for downloading and preprocessing the HCP dataset.  

For using preprocess function but want the data in pyg format, use Brain_Connectome_Rest class from NeuroGraph.
