### ISSUE TITLE
age and gender labels

### ISSUE THREAD

**Issue by amirasad76** [Anwar-Said/NeuroGraph#8]
I hope this text finds you well. I am amirhossein asadnajafi, a researcher working on a project involving age and gender classification using graph-based neural networks. I have been reviewing the datasets you have used for age and gender classification and noticed that the datasets do not contain an equal number of samples for these categories.

Could you kindly explain the reason behind this discrepancy? Additionally, I am interested in a dataset that includes both age and gender labels. Would it be possible to access such a dataset, or do you have any recommendations on how I might proceed to obtain or construct one?

I greatly appreciate your time and consideration and look forward to your response.

Best regards,
Amir hossein Asadnajafi

**Comment by Anwar-Said** [comment]
Hi,

Thanks for reaching out! Yes, in the age dataset, the fourth category for ages 36 and above was eliminated as it contained only 14 subjects (0.09%), to maintain a reasonably balanced dataset (section 3.3), due to which there is a mismatch.

Regarding your second question, you may use Neurograph (https://neurograph.readthedocs.io/en/latest/index.html) to preprocess HCP from the scratch and keep instances with both age and gender labels to work with. I hope this helps.

**Comment by amirasad76** [comment]
I am very thankful for your answer.
Best regards.

**Comment by amirasad76** [comment]
Hello
Happy New Year!  Wishing you health, happiness, and fulfillment in all your
endeavors.
I have some questions about the graphs in the data. First, I want to
know what the nodes' features are( in most cases we use one-hot encoding
for example). Next, I want to know how you obtain your graphs( correlation
or...).
Best regards
